name: Documentation Issue 📚
description: Report issues in our documentation.
labels: Issue-Docs
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: Write a descriptive title.
      required: true
- type: textarea
  attributes:
    label: Issue summary
    description: Briefly describe which document needs to be corrected and why.
  validations:
    required: true
