
parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    POWERSHELL_TELEMETRY_OPTOUT: 1
    # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

  steps:
  - script: dotnet restore PSReadLine/PSReadLine.csproj
  - script: dotnet nuget locals all --list
  - powershell: |
      Install-Module InvokeBuild,platyPS -Scope CurrentUser -Force
      Import-Module InvokeBuild,platyPS
      Invoke-Build -Task RunTests,ZipRelease -Configuration Release
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/*.trx'

