
parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    POWERSHELL_TELEMETRY_OPTOUT: 1
    # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

  steps:
  - pwsh: |
      ./build.ps1 -Bootstrap
    displayName: Bootstrap
    condition: succeededOrFailed()

  - pwsh: |
      $arguments = @{
        Configuration = 'Release'
        Framework = if ($IsWindows) {'net461'} else {'netcoreapp2.1'}
      }
      ./build.ps1 @arguments
      ./build.ps1 -Test @arguments
    displayName: Build and Test
    condition: succeeded()

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: '*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/test/TestResults'
