
parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    POWERSHELL_TELEMETRY_OPTOUT: 1
    # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

  steps:
  - pwsh: |
      ./build.ps1 -Bootstrap
    displayName: Bootstrap
    condition: succeededOrFailed()

  - pwsh: |
      ./build.ps1 -Configuration Release -Framework net461
    displayName: Build
    condition: succeeded()

  - pwsh: |
      ./build.ps1 -Test -Configuration Release -Framework net461
    displayName: xUnit Tests
    condition: succeeded()
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: '*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/test/TestResults'
